### ISSUE TITLE
nginx.conf needs to allow upload of large files

### ISSUE THREAD

**Issue by vsoch** [singularityware/singularity-hub#20]
@gmkurtzer what is a reasonable maximum size for a container?

**Comment by gmkurtzer** [comment]
Good question.... 5 is good to start off with I think and we can always increase it if necessary,... right?

Thanks!

**Comment by vsoch** [comment]
Yerp! Thanks @gmkurtzer!

**Comment by gmkurtzer** [comment]
Anytime! :-D
